import streamlit as st
from database import initialize_database
from pages import home, signup

st.set_page_config(page_title="Sentosa Massage Booking", layout="wide")

initialize_database()

st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Home", "Sign Up"])

st.sidebar.info("This app was generated by Jules, an agentic coding assistant.")

if page == "Home":
    home.app()
elif page == "Sign Up":
    signup.app()
